#!/bin/bash

for i in $(ps -cT -p $(ps aux | grep enb.conf | grep -v sudo | head -n 1 | awk '{print $2}') | grep WORKER | grep -v TASKWORKER | grep -v PRACH_WORKER | awk '{ print $2 }'); do
  echo "$i" > /sys/fs/cgroup/cpuset/user/tasks
done
